### ISSUE TITLE
Permissions in example not valid

### ISSUE THREAD

**Issue by james-callahan** [redhat-plumbers-in-action/differential-shellcheck#188]
### Type of issue

Bug Report

### Description

In the sampe in the readme you have a top level
```yaml
permissions:
  contents: read
```

as well as a `permissions` clause inside of `jobs`:
```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      pull-requests: write
```

Doing this results in the job *not* having `contents: read`, which results in a failure such as:
> Error: fatal: repository 'https://github.com/james-callahan/my-private-repo/' not found

### Describe the solution you'd like

Remove the top level `permissions` and just have:
```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      pull-requests: write
```

### Related

  - https://github.com/actions/checkout/issues/985#issuecomment-1364034319
