### ISSUE TITLE
Differential ShellCheck not detecting vulnerabilities with shell script

### ISSUE THREAD

**Issue by firoshaq** [redhat-plumbers-in-action/differential-shellcheck#453]
Dear Team,

We used the below actions with Differential ShellCheck, however it didn´t detect a vulnerable shell script that we had in the same repository.

```
name: ShellCheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Shell Scripts with ShellCheck
    runs-on: our-container
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Differential ShellCheck
        id: shellcheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5

      - name: Display ShellCheck results
        if: always()
        run: |
          if [ -n "${{ steps.shellcheck.outputs.shellcheck-output }}" ]; then
            echo "ShellCheck found issues:"
            echo "${{ steps.shellcheck.outputs.shellcheck-output }}"
          else
            echo "No ShellCheck issues found."
          fi
      - name: Upload SARIF to GitHub
        if: always() && steps.shellcheck.outputs.sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.shellcheck.outputs.sarif }}
   ```

below is the sample vulnerable shell script.

```
#!/bin/bash

# Take user input
echo "Enter a filename:"
read filename

# List files that match the input
ls $filename

# Create a temporary file
tempfile="/tmp/mytempfile"
echo "Creating temporary file at $tempfile"
touch $tempfile


# Check if a directory exists, if not create it
if [ ! -d /mydir ]; then
  mkdir /mydir
fi

# Delete all files in a directory (dangerous!)
rm /some/directory/*
```

while checking the logs we see these shell scripts were not included in the List of shell scripts for scanning, please see the snippet below.

<img width="965" alt="Screenshot 2024-10-09 at 2 22 15 PM" src="https://github.com/user-attachments/assets/e58baa7a-9b24-4aed-9e15-43d44d95514f">

Please let us know if we are missing something here.

Regards,
Firos Haq
