### ISSUE TITLE
Unexpected `execute_shellcheck` behavior

### ISSUE THREAD

**Issue by aidanSoles** [redhat-plumbers-in-action/differential-shellcheck#460]
### Type of issue

Bug (unexpected behavior).

### Description

Hi! First, this project is great. TYSM for making/maintaining it.

Second, I'm hitting some unexpected behavior with this GitHub action. After doing some digging into the container's internals (after the GitHub action wasn't behaving as I expected), it looks like calls to `execute_shellcheck` and raw `shellcheck` calls behave differently (see below, which is output from inside the container):
```
[root@8d587919ec54 workspace]# ls # A sample script with warnings.
foo.sh
[root@8d587919ec54 workspace]# cat foo.sh 
#!/bin/bash

echo 'hi there'
if [ $? -ne 0 ]; then
    echo 'success'
fi

printf "%s hey\n"
printf "hi there %s\n"
[root@8d587919ec54 workspace]# cd /action
[root@8d587919ec54 action]# source functions.sh # To source the execute_shellcheck function.
[root@8d587919ec54 action]# cd -
/github/workspace
[root@8d587919ec54 workspace]# execute_shellcheck foo.sh # Emulating the call in /action/index.sh.

[root@8d587919ec54 workspace]# echo $?
0
[root@8d587919ec54 workspace]# shellcheck foo.sh # Raw shellcheck call.

In foo.sh line 4:
if [ $? -ne 0 ]; then
     ^-- SC2320 (warning): This $? refers to echo/printf, not a previous command. Assign to variable to avoid it being overwritten.
     ^-- SC2181 (style): Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?.


In foo.sh line 8:
printf "%s hey\n"
       ^--------^ SC2183 (warning): This format string has 1 variable, but is passed 0 argument.


In foo.sh line 9:
printf "hi there %s\n"
       ^-------------^ SC2183 (warning): This format string has 1 variable, but is passed 0 argument.

For more information:
  https://www.shellcheck.net/wiki/SC2183 -- This format string has 1 variable...
  https://www.shellcheck.net/wiki/SC2320 -- This $? refers to echo/printf, no...
  https://www.shellcheck.net/wiki/SC2181 -- Check exit code directly with e.g...
[root@8d587919ec54 workspace]# echo $?
1
```
I'd expect `execute_shellcheck` and raw `shellcheck` to act the same (same output and return code), but it doesn't seem like they are.

**The questions I have are: Is this the expected behavior? Or is there a bug here? Or, do I have something misconfigured on my end (a very real possibility)?**

Last, the `job` in my GitHub actions file is as follows:
```
  shellcheck:
    runs-on: ubuntu-latest
    # The below perms are needed by Differential ShellCheck.
    permissions:
      security-events: write
      actions: read
      contents: read
    name: Run shellcheck on modified shell scripts
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          # Differential ShellCheck requires full git history
          fetch-depth: 0
          # lfs: true
      - id: differential-shellcheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          severity: style
```

TYSM. 😄

### Describe the solution you'd like

A bug fix if this is a bug, and working config options if this is a PEBKAC. ❤️
