### ISSUE TITLE
Add option to specify error level :bar_chart: 

### ISSUE THREAD

**Issue by jamacku** [redhat-plumbers-in-action/differential-shellcheck#75]
### Type of issue

Feature Request

### Description

It would make sense to allow users to specify minimal error level that should be reported by differential-shellcheck

For example when user is interested only in errors it would look like:

```yml
  - name: Differential ShellCheck
    uses: redhat-plumbers-in-action/differential-shellcheck@latest
      with:
        level: error
        token: ${{ secrets.GITHUB_TOKEN }}
```

### Describe the solution you'd like

`csgrep` has option `--event` that could be used to implement this feature:

```
--event arg
              defect matches if its key event matches the given regex (each defect has exactly one key event, which determines its location in the code)
```

I woud expect something like this:

```yml
error:    '^error'
warning:  '^warning|^error'
note:     '^note|^warning|^error' <-- default
```
