### ISSUE TITLE
Utilize Job summaries in DEBUG mode 🧰 

### ISSUE THREAD

**Issue by jamacku** [redhat-plumbers-in-action/differential-shellcheck#77]
### Type of issue

Feature Request

### Description

It would be nice to show more details when differential-shellcheck is run in DEBUG mode.

Ideas:

* Show list of changes - using `<details></details>` syntax
* Show versions of ShellCheck and csutils

**Comment by jamacku** [comment]
Fixed by:
- #110

You can now upload the SARIF file as artifact using `actions/upload-artifact` GitHub Action:

```yaml
- if: ${{ always() }}
  name: Upload artifact with ShellCheck defects in SARIF format
  uses: actions/upload-artifact@v3
  with:
    name: Differential ShellCheck SARIF
    path: ${{ steps.ShellCheck.outputs.sarif }}
```
