### ISSUE TITLE
Make SARIF reports accessible for inspections :toolbox: 

### ISSUE THREAD

**Issue by jamacku** [redhat-plumbers-in-action/differential-shellcheck#99]
### Type of issue

Feature Request

### Description

An accessible SARIF report would allow us to inspect the report quickly and will enable us to reproduce some issues locally.

/cc @kdudka

### Describe the solution you'd like

* Best solution would be to use [artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) to upload the SARIF report directly to workflow run.
* It should be made default, and we should introduce an option to disable it. And also, it should be enabled whenever an action is run in `DEBUG` mode

**Comment by jamacku** [comment]
Fixed by:
- #110

You can now upload the SARIF file as artifact using `actions/upload-artifact` GitHub Action:

```yaml
- if: ${{ always() }}
  name: Upload artifact with ShellCheck defects in SARIF format
  uses: actions/upload-artifact@v3
  with:
    name: Differential ShellCheck SARIF
    path: ${{ steps.ShellCheck.outputs.sarif }}
```
